### ISSUE TITLE
Cross-mod compatability error

### ISSUE THREAD

**Issue by Yamza** [p455w0rd/p455w0rds-Library#45]
Between this, LagGoggles, and VoxelMap.

Details are in this issue report.
https://github.com/TerminatorNL/LagGoggles/issues/71

**Comment by Gunner76th** [comment]
https://github.com/p455w0rd/p455w0rds-Library/issues/26#issuecomment-513769905

@p455w0rd Can you please address this asap and fix the problem? It would appear that almost all of the work in resolving the issue has been completed by @TerminatorNL from Lag Goggles as referenced in https://github.com/TerminatorNL/LagGoggles/issues/71#issuecomment-513765666
At this point this is causing multiple packs as well as other mods that use Mixin to crash because of how p455w0rdlib is compiled to modify the classes. Additional crash reports related to p455w0rdlib are here: 
https://github.com/TerminatorNL/LagGoggles/issues/70#issuecomment-512615356
https://github.com/p455w0rd/p455w0rds-Library/issues/27

While you may have attempted to fix the issue on June 18, it it has in fact not resolved because your mod /dank/null has not be updated to use the latest version of p455w0rdslib the ability to use version 156 of the libary is moot since any pack that contains dank/nul, wireless crafting terminal, and Just Enough Energistics (JEE) (such as StoneBlock 2 by FTB) will crash.

Attached below is a copy of 2 crash reports, as well as the debug.log and latest.log file from an attempt to use version 156 of the library that was released that is suppose to fix the above error concerning Mixin. As you can see, because your other mods were not updated at the same time they are unable to load as a result. So while having updated the library file might fix the issue when that is the only mod of yours that is used, if any mod of yours is used that depends on your library is used the pack still crashes. 
[crash-2019-08-09_11.42.09-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3487075/crash-2019-08-09_11.42.09-client.txt)
[crash-2019-08-09_11.42.08-client.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3487076/crash-2019-08-09_11.42.08-client.txt)
[debug.log](https://github.com/p455w0rd/p455w0rds-Library/files/3487079/debug.log)
[latest.log](https://github.com/p455w0rd/p455w0rds-Library/files/3487080/latest.log)

**Comment by p455w0rd** [comment]
I am always in contact with pack devs. We are aware and and it _is_ getting fixed asap. Replying to an issue only to confirm it helps nothing. Requesting things get done faster helps nothing. It just makes me stop what I'm doing to write these ridiculous replies. So, I'll happily reply to every message and never get a release out if you guys want to keep playing this game.
